on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x, 24.x ]

    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Npm install
        run: npm ci

      - name: Execute tests
        run: npm run tests
